ex_joint_goal:
  ros__parameters:
    waypoint_width: 6
    joint_waypoints_flat: [
      0.0, 0.0, -1.57, 0.0, 1.57, 0.0,
      0.3, -1.0, 1.0, 0.2, 1.0, 0.2,
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0
    ]
    pause_between_waypoints: 0.0
